---
machine_user: "fishi0x01"

arduino_ide:
  version: "1.8.13"
  checksum: "sha512:865a442ac7c2406794d93669afbff6b54a598c22bc9b6e39e5257ad8305a56cca5537aa4b19048a087688d8bf2f1fb046577f5565f66c471cbe14dd399004eb3"

cargo_packages:
- "cargo-crev"
#- "starship"

apt_packages:
- "stubby"
- "uuid"
- "libgstreamer1.0-0" 
- "gstreamer1.0-plugins-base" 
- "gstreamer1.0-plugins-good" 
- "gstreamer1.0-plugins-bad" 
- "gstreamer1.0-plugins-ugly" 
- "gstreamer1.0-gtk3"
- "pavucontrol"
- "firejail"
- "nfs-common"
- "xz-utils"
- "sl"
- "rpm2cpio"
- "libclang-dev"
- "llvm-dev"
- "clang"
- "musl-tools"
- "libssl-dev"
- "openssl"
- "anki"
- "thunderbird"
- "gcc"
- "bison"
