---
machine_user: "fishi0x01"

arduino_ide:
  version: "1.8.13"
  checksum: "sha512:865a442ac7c2406794d93669afbff6b54a598c22bc9b6e39e5257ad8305a56cca5537aa4b19048a087688d8bf2f1fb046577f5565f66c471cbe14dd399004eb3"

fritzing_ide:
  version: "0.9.4"
  url: "https://fritzing.org/download/0.9.4/ubuntu-1804/fritzing-a1ffcea08814801903b1a9515b18cf97067968ae-master-498.bionic.linux.AMD64.tar.bz2"
  checksum: "sha512:5e316de2e9c4d29b58b0cba5015d5750934014c00482f40ab0e3bcf3e72e1added436476359322bc68adc2bb8bcf4e754e8ee6346883c1a6cee0c41ea54cd4c3"

cargo_packages:
- "cargo-crev"
- "diskonaut"
- "bandwhich"
- "diesel_cli --no-default-features --features postgres"
#- "starship"

apt_packages:
- "stubby"
- "uuid"
- "libgstreamer1.0-0" 
- "gstreamer1.0-plugins-base" 
- "gstreamer1.0-plugins-good" 
- "gstreamer1.0-plugins-bad" 
- "gstreamer1.0-plugins-ugly" 
- "gstreamer1.0-gtk3"
- "pavucontrol"
- "firejail"
- "nfs-common"
- "xz-utils"
- "sl"
- "rpm2cpio"
- "libclang-dev"
- "llvm-dev"
- "clang"
- "musl-tools"
- "libssl-dev"
- "openssl"
- "anki"
- "thunderbird"
- "gcc"
- "bison"
- "libqt5printsupport5"
- "libqt5xml5"
- "libqt5sql5"
- "libqt5serialport5"
- "libqt5sql5-sqlite"
- "libc6:i386"
- "libncurses5:i386"
- "libstdc++6:i386"
- "lib32z1"
- "libbz2-1.0:i386"
- "qemu-kvm"
