---
- name: Install easy Packages
  apt:
    name: "{{ simple_packages }}"
    force_apt_get: yes
    state: present
    update_cache: yes

#################
# Wireshark Setup
#################
- name: Install Wireshark
  apt:
    name:
     - "wireshark"
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Add wireshark group
  group:
    name: "wireshark"
    state: present

- name: Add user to Wireshark Group
  user:
    name: "{{ machine_user }}"
    append: yes
    groups: wireshark

#########
# Keybase
#########
- name: Install keybase
  apt:
    deb: "https://prerelease.keybase.io/keybase_amd64.deb"
    state: present
    force_apt_get: yes

##############
# Docker Setup
##############
- name: Add docker repo key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Install docker-ce
  apt:
    name: "docker-ce"
    update_cache: yes
    force_apt_get: yes
    state: present

- name: Configure docker-ce
  template:
    src: "templates/docker-daemon.json"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "644"
  notify: 
    - "restart docker"

#############
# sysctl.conf
#############
- name: Configure inotify limits
  template:
    src: "templates/sysctl.d.inotify.conf"
    dest: "/etc/sysctl.d/10-inotify.conf"
    owner: "root"
    group: "root"
    mode: "644"
  notify: 
    - "reload sysctl"

#################
# Firefox Sandbox
#################
- name: Configure firefox sandbox desktop
  copy:
    src: files/ff-sandbox.desktop
    dest: "/home/{{ machine_user }}/Desktop/ff-sandbox.desktop"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "755"

- name: Configure firefox sandbox icon
  copy:
    src: files/ff-sandbox.png
    dest: "/home/{{ machine_user }}/.local/share/icons/ff-sandbox.png"
    owner: "{{ machine_user }}"
    group: "{{ machine_user }}"
    mode: "444"
