---
machine_user: "fishi"

simple_packages:
- "virtualbox"
- "stubby"
- "uuid"
- "libgstreamer1.0-0" 
- "gstreamer1.0-plugins-base" 
- "gstreamer1.0-plugins-good" 
- "gstreamer1.0-plugins-bad" 
- "gstreamer1.0-plugins-ugly" 
- "gstreamer1.0-gtk3"
- "firejail"
- "nfs-common"
- "xz-utils"
- "sl"
- "rpm2cpio"
- "libclang-dev"
- "llvm-dev"
- "clang"
