---
- name: Install pyenv
  become: true
  become_user: "{{ machine_user }}"
  git:
    repo: https://github.com/pyenv/pyenv
    dest: ~/.pyenv
    version: "{{ pyenv_version }}"

- name: Install global pip packages
  pip:
    executable: "{{ pip_exec }}"
    name: "{{ global_pip_packages }}"
